### ISSUE TITLE
Expanding the Lean Notes brand umbrella

### ISSUE THREAD

**Issue by stuartpb** [stuartpb/leannotes#2]
I was thinking last night about how I'm not wild about Lean Notes as a title, and how the approach I'm using here kind of mirrors the approach I intend to use for [Everybody Gets a Factory](https://github.com/stuartpb/everybody-gets-a-factory) - and the approach I've wanted to use for years for other topics such as cooking and (possibly) fitness.

As such, what might make sense - though I'm not thinking I'll do this right away - would be to give this a better subtitle (one I thought of last night was "Denting the Tech World", akin to Steve Jobs' "put a dent in the universe" line), then have separate repos where this might subsume Everybody Gets a Factory and other projects I'd undertake in the same vein.

Just a thought - like I said, I don't want to throw scope intimidation in my path right now, when I'm just starting the repo-ization of this. The extent that I think I should be looking at this right now is coming up with a better title / subtitle to share this under (which should really be a separate issue).

**Comment by stuartpb** [comment]
Okay: In light of stuartpb/how-i-roll#3 officially merging that repo into this one, that **is** the new subtitle: "How Stuart P. Bentley Rolls", and this is just the title for my magnum opus of Everything I've Ever Done or Planned to Do, What Goes Into How and Why I Did or Do It, And How and Why to Do It for Yourself as a randomly-ordered series of essays and stubs and indices and collections and whatever you'd call it.

That means Everybody Gets a Factory gets merged in, too, and maybe a bunch of other similar projects (Primer Prime, even?)

**Comment by stuartpb** [comment]
Actually, I think reviewing https://github.com/stuartpb/collected-writings and taking a mental inventory of some other projects is probably a good way to illuminate, survey, assess, and illustrate this project's boundaries:

- stuartpb-loadout: **No.** The loadout repo is more in the vein of containing a distinct, coded tool than thoughts and procedures.
- stuartpb-on-security: **Yes.** I'm pretty sure there was already at least half one board on its way to being that already.
- selling-to-help: **Yes.** Again, there are already a couple boards that were within arm's length of this one.
- barfspace: **No.** This is downstream from barfspace; barfspace is an incubator for this (which *could* be an incubator for more things, as was mentioned [here](https://github.com/stuartpb/how-i-roll/issues/3#issuecomment-422238716)).
- manual-of-style: **No.** There's a clear, demonstrated space for documents proscribing (or, in my case, describing) rigidly-followed collections of typing conventions. That's why *this* document was formed to stand out in a separate repo, while the *rest* of how-i-roll was merged here.
- petlogs: **No.** Those logs aren't general enough to follow. However, overviews of the procedures described there, at some level, may make it here.
- petboxen, as a general concept: **Yes**, but with an eye to move out (I have the org reserved for it and everything).
- github-mistakes: **No.** Like how petlogs might prove as inspiration for guides that may go here, github-mistakes may lead me to write a "How to Use GitHub (Correctly) for This" here (indeed, "How to Use GitHub Issues for Notes", on the first non-introductory item on that list, is one of the non-Lean-Notes content files coming in from how-i-roll), but it's worth keeping this document separate as an inspiration rantspace (where I can link out to Lean Notes content if I do write "responses").
- nerd-first: **Yes.** I should probably have an index page (or list on the README) for "Things I Started As Their Own Books"
- undesign: **Yes.** Seeing as how *literally all I have in that repo is a tagline*, I think I'm going to gank its listing in Collected Works (and probably more than a few of these other merged-in projects, tbh) for its Content Page here.
- Primer Prime: **Yes.** I was already drafting it on Trello, just like...
- Understanding Lua: **No,** but only because I'm not even sure what Understanding Lua is even supposed to be *documenting* any more. Is it a graphic novel script again? Is it a virtual reality application? Is it a series of YouTube videos where I play with props? (Wait. That could work. ***Shit.***) It feels like the thing that would come from Understanding Lua to Lean Notes is an exploration of *what I'm thinking about when I think about Understanding Lua*.
- Everybody Gets a Factory: Already mentioned it. **Yes.**
- Homo Socialmediis: Eh... **yes**, to what extent there's anything to merge. I might copy it in as like a paragraph on getting too lost in metrics to recognize that you're using dark patterns, but, like... I feel like the place for a lot of the ranty stuff that would go here is probably just going to be barfspace, really.
- CouchDB in a Hurry: **No**, but it's definitely getting linked in whenever I bring up writing for data stores.
- FLOC Estimation: **No** - it's too distinct and novel a concept to merge in here. I think that's a key distinguishing feature: if it's something like the LITL License or Alphabinary, it gets its own project, and lives outside of this house. (Now that I think about it, though, it *should* get a listing on https://unusual.studio/projects.)
- stuartpb-exit-codes: **No.** Honestly, I think I'm going to kick this back to barfspace and blow away the repo. Like I said in its collected-writings entry, it makes me feel like kind of a dick, and barfspace is pretty much the fence I'd want it to live behind.
- waxhead-revisited: **No.** While this is documenting how to accomplish something, something like a guide with a personal twist, most people don't need to play through The Tale of Orpheo's Curse to accomplish something they need. (Again, I think I might kick this to barfspace - it's very textfiles-y already.)
- date-rosetta: **No,** as it's another too-distinctly-its-own-utility document. That said, this is still an interesting idea (for certain values of "interesting"), and could maybe be added as like a dex 1 project for Unusual Studio.
- hoard-guidelines: **No** - it's too distinctly opinionated and strictly prescriptive - it's more like an RFC than something that'd make sense in this project.
- threejs-ways-to-do-it: **Nah.** If I ever revisit that, I'll do it within that repo. I might move it back into a series within Lean Notes at some point, but I'd need to have some distinct content by that point.
- The SACRED Manifesto: **No.** Like FLOC, it should have its own life, and get called in from here. SACRED is to the things that'll get covered here what [surpass](https://github.com/stuartpb/surpass) is to the things that I'll be merging in from stuartpb on Security.
- Meditations: Oh crap, I didn't realize this was still around, I thought it got merged into barfspace. Uh... **some of it**. I think meditations is like this little disputed territory between these two repos, but it's pretty clear where the boundary lies within content that belongs *there* and content that belongs *here* (and, wherever there's a judgement call, it can get knocked back to barfspace with an option to graduate back to here).
- stuartpb.com: **No.** If I'm merging a bunch of my other stuff into this, that may make it a big chunk of who I am, but it's not so much right now that I'd put it directly into my own namespace (beyond moving it back into my personal repo namespace on GitHub), like at a blog subdomain/subdirectory or anything like that. Like Unusual Studio, it'll live off at a distance as its own thing that could theoretically be continued by somebody else.

**Comment by stuartpb** [comment]
Going back down my whole long list of repositories to make some more calls:

- namespace-taboos: Eh, I, ehm, hmmmmmmm... hmmmmmmmmmm**yes**. This was kind of a weird thing for me to want to make a repo for in the first place, and, honestly, in some ways, this is, like, the **perfect** fit for something in Lean Notes: a collection of esoteric knowledge that doesn't really have a *place* for it, but fits into a whole bunch of *larger* concerns where it might make sense to link in. I don't know.
- GATEs and PLATEs: **Nah.** Not only are there asset files that go with this, it's also from a very different world. I mean, bottom line, it's like FLOC Estimation or HOARD, in that it's a perscriptive methodology, meaning it gets its own name and repo and whole separate thing, like a distinct project. The stuff that *does* get merged into here is the stuff that was always written vaporware, because its contours were never clearly defined.
- pitches-and-scripts: **No.** And that goes for doodles-and-riffs, too: those are *different* catch-all repos/incubators, for *different kinds of content* than the ones in this repository (the "assets" folder here is for assets that are going to be clearly used in the writing of the content, like how tags are to denote certain kinds of text - I guess the next asset to follow off from that would be custom emoji?).
- stuart-explains: Oof. I think this and Understanding Lua need to get together and work out to what extent they're different things. Essentially, this is *kind of* supposed to be merged, in spirit at least, into Lean Notes.

Well, that's pretty much everything I can think of that I've published in any way, shape, or form. I guess this'll be the big thing I work on tomorrow.

**Comment by stuartpb** [comment]
Hey, wait, I *did* start merging meditations into barfspace - that's where the-zit.md went. Maybe I got stuck feeling that not everything in Meditations should be moved there, wanting something like this?

**Comment by stuartpb** [comment]
Since Homo Socialmediis is actually completely empty, I've decided to just cut its summary from Collected Writings and dump that into barfspace, since that fits its ranty speed a lot more (especially if I do end up [ganking the hyperhairball design of this repo over there](stuartpb/barfspace#9)).

**Comment by stuartpb** [comment]
Okay, I'm deleting or archiving the merged-in repositories now:

## Deleting

- [x] stuartpb-on-security (haven't deleted the workspace yet, though)
- [x] selling-to-help
- [x] undesign
- [x] homo-socialmediis
- [x] namespace-taboos

## Archiving

- [x] meditations
- [x] nerd-first (archiving because it has [an interesting open PR](https://github.com/stuartpb/nerd-first/pull/1))
- [x] everybody-gets-a-factory (archived because it has [open issues](https://github.com/stuartpb/everybody-gets-a-factory/issues))
- [x] primerprime

**Comment by stuartpb** [comment]
Okay, the big things I want to do now are:

- Document the "bagtent" structure in a separate repo (with tooling)
- Document the Musings <-> Meditations gateway in barfspace
- Maybe start backpressuring Mediatations into Barfspace, so that all the poesy cryptic stuff can live over there, and all the clear stuff with explanations and examples can live here

**Comment by stuartpb** [comment]
All of this is now being done within notes.stuartpb.com (the "structure" is kind of readily self-apparent; I've started gathering notes on other similar projects I'm finding, which is much more interesting)
